// modules/constants.js
// All top-level application constants.
// No logic — pure data and configuration.

// ── API ENDPOINTS ────────────────────────────────────────────────
export const API_URL        = 'https://toody-api.vercel.app/api/generate';
export const TRANSCRIBE_URL = 'https://toody-api.vercel.app/api/transcribe';
export const AUDIO_URL      = 'https://toody-api.vercel.app/api/audio';

export const SKILL_CATALOGUE = [
  { skill: 'reading.tfng',              screen: 's-reading',   section: 'Reading',   label: 'True / False / Not Given',    icon: '📖', desc: 'AI-generated passage + 5 TF/NG questions. Toody explains every answer.' },
  { skill: 'reading.summaryCompletion',  screen: 's-reading',   section: 'Reading',   label: 'Summary Completion',           icon: '📖', desc: 'Complete a gapped summary using a word bank.' },
  { skill: 'reading.yesNoNotGiven',     screen: 's-reading',   section: 'Reading',   label: 'Yes / No / Not Given',         icon: '📖', desc: "Decide if statements match the writer's views." },
  { skill: 'reading.multipleChoice',    screen: 's-reading',   section: 'Reading',   label: 'Multiple Choice',              icon: '📖', desc: 'Choose the best answer from four options about a reading passage.' },
  { skill: 'reading.sentenceCompletion',screen: 's-reading',   section: 'Reading',   label: 'Sentence Completion',          icon: '📖', desc: 'Complete sentences using words directly from the passage.' },
  { skill: 'listening.multipleChoice',  screen: 's-listening', section: 'Listening', label: 'Multiple Choice',              icon: '🎧', desc: 'Pick the correct answer from detailed audio scenarios.' },
  { skill: 'listening.formCompletion',  screen: 's-listening', section: 'Listening', label: 'Form Completion',              icon: '🎧', desc: 'Complete a form from information in the audio.' },
  { skill: 'writing.task1',             screen: 's-writing',   section: 'Writing',   label: 'Task 1 — Graph Description',   icon: '✍️', desc: 'Describe an academic graph or chart in 150+ words.' },
  { skill: 'writing.task2',             screen: 's-writing',   section: 'Writing',   label: 'Task 2 — Opinion Essay',       icon: '✍️', desc: 'Write a 250-word academic opinion essay.' },
  { skill: 'speaking.part1',            screen: 's-speaking',  section: 'Speaking',  label: 'Part 1 — Personal Questions',  icon: '🎤', desc: 'Answer personal questions. Transcribed and evaluated.' },
];

// Fast lookup by skill key
export const SKILL_MAP = Object.fromEntries(SKILL_CATALOGUE.map(s => [s.skill, s]));


// Hook trap question — hardcoded, no instructions, hooks on NG confusion
export const HOOK_TRAP = {
  passage: 'Recent studies suggest that urban air pollution has decreased in major cities over the last decade. Researchers attribute this to stricter vehicle emission standards introduced in 2015.',
  statement: 'The reduction in urban air pollution has improved the mental health of city residents.',
  answer: 'NG',
  explanation: 'The passage confirms pollution has decreased in major cities — but it says nothing about mental health. The statement introduces a new claim the passage never addresses. This is Not Given: the passage is simply silent on this point.',
  keySentence: 'Recent studies suggest that urban air pollution has decreased in major cities over the last decade.',
  insight: "This is the Cautious Language Trap. The passage uses the word 'suggest' — not 'proves' or 'confirms.' When a passage uses cautious language — words like suggest, may, could, or appears to — it is NOT confirming the statement as true. But it is also not contradicting it. The passage is simply uncertain. Uncertain = Not Given, not False. False means the passage says the opposite. This passage never says the opposite — it uses cautious language.",
};

// Hardcoded expert-verified T/F/NG worked examples.
// Used in the Teach-First phase for reading-tfng instead of AI generation,
// so every student sees the same battle-tested explanations for the three
// core answer types. AI generates everything else (hook, concept, confidence,
// drill). Only these three examples are locked.
export const TFNG_WORKED_EXAMPLES = [
  {
    label: 'Example 1 — The Direct Clash (clearly FALSE)',
    passage: 'The construction of the Great Pyramid was completed in approximately 20 years using a workforce of skilled labourers, not slaves.',
    statement: 'The Great Pyramid was built by people who were forced to work against their will.',
    answer: 'False',
    bandFiveAnswer: 'True',
    bandFiveReason: 'They see "Great Pyramid" and "built" and assume ancient construction means forced labour.',
    explanation: 'The passage says "skilled labourers" and specifically says "not slaves." The statement says "forced to work against their will" — that is the definition of a slave. The passage says A and the statement says Not A. They are directly contradicting each other. When two things directly contradict — that is False.',
    trap: 'none — this is the clearest case. If a student gets this wrong they have a fundamental False vs Not Given confusion.',
    teachingNote: 'This is the clearest case. True means the passage confirms it. False means the passage says the opposite. Here the passage explicitly says not slaves — the opposite of forced labour.',
  },
  {
    label: 'Example 2 — The Missing Link (clearly NOT GIVEN)',
    passage: 'Recent studies show that drinking green tea can lead to a significant reduction in high blood pressure among middle-aged adults.',
    statement: 'Green tea is more effective at lowering blood pressure than black tea.',
    answer: 'Not Given',
    bandFiveAnswer: 'True',
    bandFiveReason: 'They see green tea and blood pressure and assume the comparison with black tea is implied.',
    explanation: 'Does the passage mention green tea? Yes. Does it mention blood pressure? Yes. Now look for black tea. Is it there? No. You might know from your own life that green tea is healthier — but the text does not compare the two. The text is completely silent about black tea. If the text is silent, you must be silent. We do not know, so it is Not Given.',
    trap: 'INFERENCE TRAP — student uses outside knowledge to fill a gap the text never bridged.',
    teachingNote: 'Not Given means the passage is simply missing this piece of the puzzle. The text does not say green tea is better or worse than black tea. It does not mention black tea at all. Silence is not agreement and silence is not contradiction.',
  },
  {
    label: 'Example 3 — The Assumption Trap (NOT GIVEN that looks like False)',
    passage: 'The local council has decided to ban all motor vehicles from the city centre during the annual summer festival to ensure pedestrian safety.',
    statement: 'The city centre will be completely quiet during the summer festival.',
    answer: 'Not Given',
    bandFiveAnswer: 'False',
    bandFiveReason: 'They think: a festival with no cars must be loud so quiet is False. Or no cars means less noise so True. Both are wrong for the same reason — they are guessing.',
    explanation: 'This is the one that trips everyone up. You are thinking: no cars means quiet. Or: it is a festival so it will be loud. Stop. Does the text use the word quiet or noisy? No. It only talks about safety and vehicles. Maybe the festival has 500 drummers. Maybe it is a silent meditation festival. We have zero evidence about noise level. You are guessing based on logic. In IELTS guessing is a crime. If the evidence is not on the paper the answer is Not Given.',
    trap: 'ASSUMPTION TRAP — student builds a logical bridge the passage never constructed. Safety and silence are different concepts.',
    teachingNote: 'Ask yourself: can I underline the word quiet or noisy anywhere in the passage? No. Then I cannot say True or False about noise. The passage is silent on this point. That silence is Not Given.',
  },
];

// ── SKILL MANIFEST — single source of truth for all skill configuration ────
// Every field that varies per skill lives here. No hardcoded skill comparisons
// anywhere else in the app. To add a skill: add one entry here.
//
// Fields:
//   id               — hyphen-id used in Firestore and SKILL_MANIFEST keys
//   catalogueKey     — dot-notation key in SKILL_CATALOGUE/SKILL_MAP, or null if not yet deployed
//   displayName      — short label shown in UI
//   section          — 'Reading' | 'Listening' | 'Writing' | 'Speaking'
//   icon             — emoji
//   description      — one-line description for the home screen card
//   answerButtons    — array of answer values (drives button rendering + NG visibility)
//   hookStyle        — 'tfng'|'ynng'|'gapfill'|'multiplechoice'|'matching'|'shortanswer'|'openended'
//   workedExamples   — 'hardcoded' | 'ai-generated'
//   conceptBubble    — HTML string shown in the concept phase header bubble
//   conceptPromptHint — AI prompt fragment for generating concept bullets
//   hookPromptHint   — AI prompt fragment for the hook question statement
//   prerequisite     — skillId that must be mastered before this skill unlocks, or null
//   accuracyGate     — minimum accuracy % required on prerequisite, or null
export const SKILL_MANIFEST = {
  'reading-tfng': {
    id:               'reading-tfng',
    catalogueKey:     'reading.tfng',
    displayName:      'True / False / Not Given',
    section:          'Reading',
    icon:             '📖',
    description:      'AI-generated passage + 5 TF/NG questions. Toody explains every answer.',
    answerButtons:    ['True', 'False', 'Not Given'],
    hookStyle:        'tfng',
    workedExamples:   'hardcoded',
    conceptBubble:    `Before we start, let me show you <strong>exactly</strong> how True / False / Not Given works — and the mistake most students make.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about True/False/Not Given. Cover: True (passage confirms), False (passage contradicts), Not Given (passage is silent — NOT False!), the #1 mistake (confusing False with Not Given). Explanation bullets only — no illustrative examples embedded in the bullets. Use ** around 1-2 key words per bullet. CRITICAL: If any example appears it must follow these rules — a passage that uses reporting verbs to present a debate (argue, believe, suggest, contend) is NOT stating a fact: that answer is Not Given not False. A passage using cautious language (may, suggests, could, appears to) is NOT confirming a statement: that answer is Not Given not True. Only mark False when the passage explicitly states the opposite as fact.`,
    hookPromptHint:   'a testable claim that looks True but is actually Not Given',
    prerequisite:     null,
    accuracyGate:     null,
  },
  'reading-summaryCompletion': {
    id:               'reading-summaryCompletion',
    catalogueKey:     'reading.summaryCompletion',
    displayName:      'Summary Completion',
    section:          'Reading',
    icon:             '📖',
    description:      'Complete a gapped summary using a word bank.',
    answerButtons:    [],
    hookStyle:        'gapfill',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you <strong>exactly</strong> how Summary Completion works — and why students lose marks.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Summary Completion. Cover: what it tests (locating specific information), the #1 mistake (using wrong word form or changing meaning), how to avoid it. No paragraph text. Use ** around 1-2 key words per bullet.`,
    hookPromptHint:   'a summary sentence with one blank gap where the instinctive fill word uses the wrong form (e.g. noun instead of adjective)',
    prerequisite:     'reading-tfng',
    accuracyGate:     75,
  },
  'reading-multipleChoice': {
    id:               'reading-multipleChoice',
    catalogueKey:     'reading.multipleChoice',
    displayName:      'Multiple Choice',
    section:          'Reading',
    icon:             '📖',
    description:      'Choose the best answer from four options about a reading passage.',
    answerButtons:    ['A', 'B', 'C', 'D'],
    hookStyle:        'multiplechoice',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Reading Multiple Choice works — and how distractors are designed to mislead.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Reading Multiple Choice. Cover: how distractors work (mentioned but not the correct answer), how to check all options carefully, elimination strategy. Use ** around key terms.`,
    hookPromptHint:   'a multiple choice question where the obvious option is a distractor',
    prerequisite:     'reading-tfng',
    accuracyGate:     75,
  },
  'reading-matchingHeadings': {
    id:               'reading-matchingHeadings',
    catalogueKey:     null,
    displayName:      'Matching Headings',
    section:          'Reading',
    icon:             '📖',
    description:      'Match headings to paragraphs — test main idea recognition.',
    answerButtons:    ['A', 'B', 'C', 'D', 'E'],
    hookStyle:        'matching',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you <strong>exactly</strong> how Matching Headings works — and the trap most students fall into.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Matching Headings. Cover: what it tests (main idea of paragraph, not details), the #1 trap (picking heading from a word match not the main idea), how to avoid it. No paragraph text. Use ** around 1-2 key words per bullet.`,
    hookPromptHint:   'a testable claim that looks True but is actually False — a detail matches but not the main idea',
    prerequisite:     'reading-tfng',
    accuracyGate:     75,
  },
  'reading-matchingInformation': {
    id:               'reading-matchingInformation',
    catalogueKey:     null,
    displayName:      'Matching Information',
    section:          'Reading',
    icon:             '📖',
    description:      'Find which paragraph contains specific information.',
    answerButtons:    ['A', 'B', 'C', 'D', 'E'],
    hookStyle:        'matching',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Matching Information works.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Matching Information. Cover: scanning vs reading, how to match specific details to paragraphs, common mistakes. Use ** around key terms.`,
    hookPromptHint:   'a matching information question where the detail appears in an unexpected paragraph',
    prerequisite:     'reading-matchingHeadings',
    accuracyGate:     75,
  },
  'reading-matchingFeatures': {
    id:               'reading-matchingFeatures',
    catalogueKey:     null,
    displayName:      'Matching Features',
    section:          'Reading',
    icon:             '📖',
    description:      'Match statements to a list of features — people, dates, or places.',
    answerButtons:    ['A', 'B', 'C', 'D', 'E'],
    hookStyle:        'matching',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Matching Features works.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Matching Features. Cover: types of features (names, dates, places), how to scan for specific entities, trap of similar-sounding features. Use ** around key terms.`,
    hookPromptHint:   'a matching features question where two similar features could both apply',
    prerequisite:     'reading-matchingHeadings',
    accuracyGate:     75,
  },
  'reading-sentenceCompletion': {
    id:               'reading-sentenceCompletion',
    catalogueKey:     'reading.sentenceCompletion',
    displayName:      'Sentence Completion',
    section:          'Reading',
    icon:             '📖',
    description:      'Complete sentences using words directly from the passage.',
    answerButtons:    [],
    hookStyle:        'gapfill',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Sentence Completion works — and the word limit trap.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Sentence Completion. Cover: always using words from the passage (not paraphrases), word limit rules (no more than 3 words), paraphrase detection. Use ** around key terms.`,
    hookPromptHint:   'a sentence completion gap where using a paraphrase instead of the exact passage word loses the mark',
    prerequisite:     'reading-summaryCompletion',
    accuracyGate:     75,
  },
  'reading-shortAnswer': {
    id:               'reading-shortAnswer',
    catalogueKey:     null,
    displayName:      'Short Answer',
    section:          'Reading',
    icon:             '📖',
    description:      'Answer questions in three words or fewer from the passage.',
    answerButtons:    [],
    hookStyle:        'shortanswer',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Short Answer Questions work — and why students lose easy marks.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Short Answer Questions. Cover: strict word limit (NO MORE THAN 3 WORDS), must use exact words from passage, what happens if you exceed the limit. Use ** around key terms.`,
    hookPromptHint:   'a short answer question where students exceed the word limit or paraphrase',
    prerequisite:     'reading-summaryCompletion',
    accuracyGate:     75,
  },
  'reading-yesNoNotGiven': {
    id:               'reading-yesNoNotGiven',
    catalogueKey:     'reading.yesNoNotGiven',
    displayName:      'Yes / No / Not Given',
    section:          'Reading',
    icon:             '📖',
    description:      "Decide if statements agree with the writer's views.",
    answerButtons:    ['Yes', 'No', 'Not Given'],
    hookStyle:        'ynng',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you <strong>exactly</strong> how Yes / No / Not Given works — and how it differs from True / False / Not Given.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about Yes/No/Not Given. Cover: YES means the writer agrees, NO means the writer disagrees (not a factual contradiction), Not Given means the writer doesn't address the claim, key difference from TFNG (opinion vs fact). Use ** around 1-2 key words per bullet.`,
    hookPromptHint:   "a claim about the writer's opinion that looks like Yes but is actually Not Given",
    prerequisite:     'reading-tfng',
    accuracyGate:     75,
  },
  'listening-multipleChoice': {
    id:               'listening-multipleChoice',
    catalogueKey:     'listening.multipleChoice',
    displayName:      'Multiple Choice',
    section:          'Listening',
    icon:             '🎧',
    description:      'Pick the correct answer from detailed audio scenarios.',
    answerButtons:    ['A', 'B', 'C'],
    hookStyle:        'multiplechoice',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Listening Multiple Choice works — and the distractor trap.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Listening Multiple Choice. Cover: how distractors work (mentioned but not the answer), the importance of predicting before listening, and how to eliminate wrong options. Use ** around key terms.`,
    hookPromptHint:   'a multiple choice question where the obvious answer is a distractor',
    prerequisite:     null,
    accuracyGate:     null,
  },
  'listening-formCompletion': {
    id:               'listening-formCompletion',
    catalogueKey:     'listening.formCompletion',
    displayName:      'Form Completion',
    section:          'Listening',
    icon:             '🎧',
    description:      'Complete a form from information in the audio.',
    answerButtons:    [],
    hookStyle:        'gapfill',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Listening Form Completion works — and how to avoid spelling traps.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Listening Form Completion. Cover: how answers are always spelled out or obvious, the importance of word limits, and common trap categories (numbers, names, spelling). Use ** around key terms.`,
    hookPromptHint:   'a form completion gap where the word limit is the trap',
    prerequisite:     'listening-multipleChoice',
    accuracyGate:     75,
  },
  'writing-task1': {
    id:               'writing-task1',
    catalogueKey:     'writing.task1',
    displayName:      'Task 1 — Graph Description',
    section:          'Writing',
    icon:             '✍️',
    description:      'Describe an academic graph or chart in 150+ words.',
    answerButtons:    [],
    hookStyle:        'openended',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Writing Task 1 works — and the key features you must cover.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Writing Task 1. Cover: overview first, selecting key features, not describing every data point, avoiding personal opinion. Use ** around key terms.`,
    hookPromptHint:   'a graph description task with a common mistake in selecting key trends',
    prerequisite:     null,
    accuracyGate:     null,
  },
  'writing-task2': {
    id:               'writing-task2',
    catalogueKey:     'writing.task2',
    displayName:      'Task 2 — Opinion Essay',
    section:          'Writing',
    icon:             '✍️',
    description:      'Write a 250-word academic opinion essay.',
    answerButtons:    [],
    hookStyle:        'openended',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Writing Task 2 works — and what examiners look for.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Writing Task 2. Cover: clear position in the introduction, one idea per paragraph, examples with specific details, not just listing ideas. Use ** around key terms.`,
    hookPromptHint:   'a Task 2 essay with an unclear or missing position in the introduction',
    prerequisite:     'writing-task1',
    accuracyGate:     null,
  },
  'speaking-part1': {
    id:               'speaking-part1',
    catalogueKey:     'speaking.part1',
    displayName:      'Part 1 — Personal Questions',
    section:          'Speaking',
    icon:             '🎤',
    description:      'Answer personal questions. Transcribed and evaluated.',
    answerButtons:    [],
    hookStyle:        'openended',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Speaking Part 1 works — and what separates Band 6 from Band 7.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Speaking Part 1. Cover: extending answers (not just yes/no), natural language vs scripted phrases, giving examples and reasons. Use ** around key terms.`,
    hookPromptHint:   'a personal question where students give one-word or one-sentence answers',
    prerequisite:     null,
    accuracyGate:     null,
  },
  'speaking-part2': {
    id:               'speaking-part2',
    catalogueKey:     null,
    displayName:      'Part 2 — Long Turn',
    section:          'Speaking',
    icon:             '🎤',
    description:      'Speak for 2 minutes on a given topic card.',
    answerButtons:    [],
    hookStyle:        'openended',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Speaking Part 2 works — and how to structure your 2-minute talk.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Speaking Part 2. Cover: using the 1-minute preparation time, covering all bullet points on the cue card, signposting your talk, what to do if you run out of things to say. Use ** around key terms.`,
    hookPromptHint:   'a Part 2 cue card where students forget to cover all bullet points',
    prerequisite:     'speaking-part1',
    accuracyGate:     null,
  },
  'speaking-part3': {
    id:               'speaking-part3',
    catalogueKey:     null,
    displayName:      'Part 3 — Discussion',
    section:          'Speaking',
    icon:             '🎤',
    description:      'Discuss abstract topics with the examiner.',
    answerButtons:    [],
    hookStyle:        'openended',
    workedExamples:   'ai-generated',
    conceptBubble:    `Before we start, let me show you how IELTS Speaking Part 3 works — and how to develop abstract ideas coherently.`,
    conceptPromptHint: `An array of 4-5 short bullet strings about IELTS Speaking Part 3. Cover: giving opinions with reasons, speculating about hypothetical scenarios, showing range of vocabulary and grammar. Use ** around key terms.`,
    hookPromptHint:   'an abstract discussion question where students give surface-level answers',
    prerequisite:     'speaking-part2',
    accuracyGate:     null,
  },
};
